services:
  
  docker-dind:
    container_name: docker-dind
    image: docker:27.3.1-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-dind-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - 2376:2376
    networks:
      jenkins:
        aliases:
          - docker
    restart: unless-stopped
    
  jenkins:
    container_name: jenkins
    image: jenkins:2.479.1-jdk17-custom
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-dind-certs:/certs/client:ro
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins
    restart: unless-stopped

  jenkins-agent:
    container_name: jenkins-agent
    image: jenkins/inbound-agent:3283.v92c105e0f819-1-jdk17-custom
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=${JENKINS_SECRET}
      - JENKINS_AGENT_NAME=jenkins-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - jenkins-data:/home/jenkins
    networks:
      - jenkins
    restart: unless-stopped

volumes:
  jenkins-data:
  docker-dind-certs:

networks:
  jenkins:
    external: true
