services:

  jenkins-server:
    container_name: jenkins-server
    image: jenkins:2.479.1-jdk17-custom
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins
    restart: unless-stopped

  jenkins-agent:
    container_name: jenkins-agent
    image: jenkins/inbound-agent:3283.v92c105e0f819-1-jdk17-custom
    environment:
      - JENKINS_URL=http://jenkins-server:8080
      - JENKINS_SECRET=${JENKINS_SECRET}
      - JENKINS_AGENT_NAME=jenkins-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/home/jenkins
    networks:
      - jenkins
    restart: unless-stopped

volumes:
  jenkins-data:

networks:
  jenkins:
    external: true
