services:
  
  docker-dind:
    container_name: docker-dind
    image: docker:27.3.1-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-dind-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - 2376:2376
    networks:
      - jenkins
    restart: unless-stopped
    
  jenkins:
    container_name: jenkins
    image: jenkins:2.479.1-jdk17-custom
    environment:
      - DOCKER_HOST=tcp://docker-dind:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-dind-certs:/certs/client:ro
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins
    restart: unless-stopped

volumes:
  jenkins-data:
  docker-dind-certs:

networks:
  jenkins:
    external: true
